### ISSUE TITLE
Attribute Error when using set_address() method

### ISSUE THREAD

**Issue by DewiDawg** [truckershitch/truckershitch-micropython-vl53l0x#1]
Hi truckershitch

Huge thanks for the port to 'standard' micropython.
I've just hit a problem using the set_address() method - I get an error when I use it, like this....

_VL53L0X Sensor Found.
Traceback (most recent call last):
  File "<stdin>", line 30, in <module>
  File "vl53l0x.py", line 575, in set_address
AttributeError: 'I2C' object has no attribute 'device_address'_

I'm pretty new to all this, but it looks like the very last line in the code is the issue

Any thoughts???

**Comment by DewiDawg** [comment]
UPDATE:
I changed line 575 to
_self._addr = new.address_
and it all seems to work. I think the old line 575 was the original CircuitPython code

**Comment by truckershitch** [comment]
Thanks @DewiDawg !

Fixed and committed.
