### ISSUE TITLE
MemoryError: memory allocation failed, allocating 1151 bytes

### ISSUE THREAD

**Issue by varna9000** [truckershitch/truckershitch-micropython-vl53l0x#2]
Doesn't fit in esp8266 memory, loaded as regular module.

**Comment by truckershitch** [comment]
How much memory does your esp8266 have? Did you consider using `mpy-cross` to compile the module as native machine code in an `.mpy` file?

See https://docs.micropython.org/en/latest/develop/natmod.html

**Comment by varna9000** [comment]
Yes, I remembered I can freeze the module after I opened the issue :) Just did mpy-cross and it worked.  Thanks for the port!

**Comment by truckershitch** [comment]
No problem!  I'm glad it is working for you.
